[theme]
# Primary accent color for interactive elements.
primaryColor="#007bff"

# Base theme (light or dark)
# base="light"

# Background color for the main content area.
# backgroundColor="#ffffff"

# Background color used for the sidebar and most interactive widgets.
# secondaryBackgroundColor="#f0f2f6"

# Color used for almost all text.
# textColor="#31333F"

# Font family for all text in the app, except code blocks.
# Supported fonts: "sans serif", "serif", "monospace"
# font="sans serif" 